version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
    cooldown:
      default-days: 1
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "21:00"
      timezone: "Europe/Helsinki"
