version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: "nuget"
    directory: "/"
    allow:
      - dependency-type: "all"
    cooldown:
      default-days: 1
      exclude:
        - "Microsoft.*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    cooldown:
      default-days: 0
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "21:00"
      timezone: "Europe/Helsinki"
