<Project>
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <AnalysisMode>all</AnalysisMode>
    <AnalysisLevel>latest</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforeCodeStyleInBuild>true</EnforeCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnableCodeAnalysis>true</EnableCodeAnalysis>
    <NoWarn>CA2007;S1135</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <NoWarn>$(NoWarn);CA1707;CA1812;CA1852;CA1515;CA1711</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Benchmarks'))">
    <NoWarn>$(NoWarn);CS0649;CA1515;CA1812;CA1051;S1104;CA1024</NoWarn>
  </PropertyGroup>
</Project>
