<Project>
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <AnalysisMode>all</AnalysisMode>
    <AnalysisLevel>latest</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforeCodeStyleInBuild>true</EnforeCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnableCodeAnalysis>true</EnableCodeAnalysis>
    <NoWarn>CA2007;S1135</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <NoWarn>$(NoWarn);CA1707;CA1812;CA1852;CA1515;CA1711</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Benchmarks'))">
    <NoWarn>$(NoWarn);CS0649;CA1515;CA1812;CA1051;S1104;CA1024</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>Tsingis</Authors>
    <Version>1.0.0</Version>
    <PackageTags>spreadsheet;excel;xlsx</PackageTags>
    <Description>Package for quickly creating spreadsheets</Description>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/Tsingis/SpreadsheetGen</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Tsingis/SpreadsheetGen</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
