<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>SpreadsheetGen</PackageId>
    <PackageReadmeFile>nuget.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="nuget.md" Pack="true" PackagePath="" />
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\resources\logo.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
