name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.props"
      - ".github/workflows/test.yml"
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            framework: net9.0
          - os: ubuntu-latest
            framework: net10.0
          - os: windows-latest
            framework: net9.0
          - os: windows-latest
            framework: net10.0
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --framework ${{ matrix.framework }} --no-restore
      - name: Test & collect coverage
        shell: bash
        run: |
          dotnet test -c Release --framework ${{ matrix.framework }} --no-restore --no-build -- \
          --coverage --coverage-output-format xml --coverage-output ${{ github.workspace }}/coverage.xml
      - name: Install Report Generator
        if: matrix.os == 'ubuntu-latest' && matrix.framework == 'net9.0'
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.framework == 'net9.0'
        shell: pwsh
        run: |
          reportgenerator -reports:"${{ github.workspace }}/**/coverage.xml" `
                          -targetdir:"coverage-report" `
                          -reporttypes:MarkdownSummaryGithub
      - name: Upload coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.framework == 'net9.0'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
      - name: Show coverage in summary
        if: matrix.os == 'ubuntu-latest' && matrix.framework == 'net9.0'
        shell: pwsh
        run: |
          Get-Content coverage-report/SummaryGithub.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
